param(
    [Parameter(Mandatory = $true)]
    [string]$ConfigPath
)

$ErrorActionPreference = 'Stop'
$project = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$config = (Resolve-Path -LiteralPath $ConfigPath).Path
$testRunsRoot = Join-Path $project 'data\test-runs'
if (-not $config.StartsWith($testRunsRoot + [IO.Path]::DirectorySeparatorChar,
        [StringComparison]::OrdinalIgnoreCase)) {
    throw 'ConfigPath must be a file generated by seed-test-server.ps1 under data/test-runs.'
}
$configText = Get-Content -LiteralPath $config -Raw
if (-not $configText.Contains('server_url = "http://127.0.0.1:18081"')) {
    throw 'This script only sends to the isolated test server at 127.0.0.1:18081.'
}

$oldToken = $env:RADIATION_PI_TOKEN
$oldPythonPath = $env:PYTHONPATH
try {
    $env:RADIATION_PI_TOKEN = 'pi-integration-device-token-only'
    $env:PYTHONPATH = Join-Path $project 'src'
    Push-Location $project
    try {
        python -m radiation_pi --config $config simulate --samples 10 --seed 7 `
            --warning-every 2 --spike-every 3 --failure-every 5 --send
        if ($LASTEXITCODE -ne 0) {
            throw "Emulator exited with code $LASTEXITCODE. Inspect its outbox before retrying."
        }
        $outboxState = python -m radiation_pi --config $config outbox-status
        if ($LASTEXITCODE -ne 0) { throw 'Could not inspect the test outbox.' }
        Write-Output $outboxState
        if (($outboxState -join "`n").Trim() -ne '[]') {
            throw 'The test outbox is not empty. Inspect pending or blocked messages.'
        }
    } finally {
        Pop-Location
    }
} finally {
    $env:RADIATION_PI_TOKEN = $oldToken
    $env:PYTHONPATH = $oldPythonPath
}

$measurements = Invoke-RestMethod -Uri 'http://127.0.0.1:18081/api/measurements' -TimeoutSec 5
$heartbeats = Invoke-RestMethod -Uri 'http://127.0.0.1:18081/api/heartbeat' -TimeoutSec 5
$events = Invoke-RestMethod -Uri 'http://127.0.0.1:18081/api/events' -TimeoutSec 5
$eventTypes = @($events | ForEach-Object { $_.eventType })
if (@($measurements).Count -ne 8) {
    throw "Expected 8 measurements after 2 simulated read failures, got $(@($measurements).Count)."
}
if (@($heartbeats).Count -lt 3) {
    throw "Expected at least 3 heartbeats, got $(@($heartbeats).Count)."
}
foreach ($required in @('RADIATION_WARNING', 'RADIATION_ALARM', 'RADIATION_NORMAL')) {
    if ($required -notin $eventTypes) { throw "Missing expected event: $required" }
}
Write-Host "Test run passed: $(@($measurements).Count) measurements, $(@($heartbeats).Count) heartbeats."
Write-Host "Events: $($eventTypes -join ', ')"
Write-Host 'Dashboard: http://127.0.0.1:18081/'
